### ISSUE TITLE
BUG: samples command/downloadSample function fails to find convert.yaml in github repo

### ISSUE THREAD

**Issue by jkeane** [MikeHopcroft/labyrinth#22]
convert.yaml files were renamed to graph.yaml.  Download URI needs to be updated.

**Comment by MikeHopcroft** [comment]
Commit 92dad5aa63dc59f514a328665e0b654909886845 fixes this issue. Leaving it open until I publish npm package version 0.0.8.

**Comment by MikeHopcroft** [comment]
Fixed in https://github.com/MikeHopcroft/labyrinth/releases/tag/v0.0.8. 
NPM Package: https://www.npmjs.com/package/labyrinth-nsg/v/0.0.8
